// Generate deployment metadata without modifying a tracked source file.
// Cloudflare Pages provides CF_PAGES_COMMIT_SHA during its build. GitHub Actions
// and a local checkout have their own fallbacks for the same deterministic identity.

import { writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { CONTENT_CONTRACT_VERSION } from "../ecology/content/index.mjs";

function nonEmpty(value) {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

let commitSha = nonEmpty(process.env.CF_PAGES_COMMIT_SHA)
  || nonEmpty(process.env.GITHUB_SHA);
if (!commitSha) {
  try {
    commitSha = nonEmpty(execFileSync("git", ["rev-parse", "--verify", "HEAD"], { encoding: "utf8" }));
  } catch {
    // A source archive without Git metadata is still usable locally.
  }
}

const build = commitSha || "local";
const outputPath = process.env.BUILD_METADATA_OUTPUT
  ? pathToFileURL(resolve(process.env.BUILD_METADATA_OUTPUT))
  : new URL("../core/build.generated.mjs", import.meta.url);
const output = [
  "// generated by analysis/stamp.mjs; do not commit",
  "export const BUILD = " + JSON.stringify(build) + ";",
  "export default BUILD;",
  "",
].join("\n");

writeFileSync(outputPath, output);
console.log("core/build.generated.mjs:", build, "fingerprint:", CONTENT_CONTRACT_VERSION);
