// 公開版の build 印を更新する。
// FINGERPRINT は現行 ecology content contract の版で、BUILD は commit と時刻である。

import { writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { CONTENT_CONTRACT_VERSION } from "../ecology/content/index.mjs";

let shortSha = process.env.GITHUB_SHA ? process.env.GITHUB_SHA.slice(0, 7) : "local";
try {
  shortSha = execFileSync("git", ["rev-parse", "--short=7", "HEAD"], { encoding: "utf8" }).trim();
} catch {
  // GitHub Actions 外では、環境変数または local を使う。
}

const when = new Date().toISOString().replace(".000Z", "Z");
const build = shortSha + " / " + when;
const output = [
  "// generated by analysis/stamp.mjs",
  "export const BUILD = " + JSON.stringify(build) + ";",
  "export const FINGERPRINT = " + JSON.stringify(CONTENT_CONTRACT_VERSION) + ";",
  "export default BUILD;",
  "",
].join("\n");

writeFileSync(new URL("../core/build.mjs", import.meta.url), output);
console.log("core/build.mjs:", build, "fingerprint:", CONTENT_CONTRACT_VERSION);
